
-- CREATE TABLE
CREATE TABLE CALL_MSG (
    CALLER_ID   VARCHAR(20)  ,
    RECEIVER_ID VARCHAR(20)  ,
    TYPE        VARCHAR(10)  ,
    MESSAGE     VARCHAR(200)
);

-- CREATE PRIMARY KEY INDEX

-- CREATE INDEX
